### PR TITLE
Fixed #61 multiple dropdown open at once

### LINKED ISSUE #61: Drop down menus do not close automatically
Drop down menu items in nav, stay open. They should close automatically when another drop-down menu is open.

### PR DESCRIPTION
**Pull request by rathod-sahaab**

### CODE REVIEW

**Comment by theamanjs** [comment]
@drossberg I've tested this PR on local and it is working as expected and mentioned in issue #61 

Side note, when you'll merge this PR please change the commit message to imperative mode. It will help to keep the commit messages consistent :)

**Comment by drossberg** [comment]
@rathod-sahaab unfortunately, your patch won't work with the new directory structure. Do you want to update it, because it looks like it's acceptable. Otherwise, we will do it for you.

**Comment by rathod-sahaab** [comment]
> @rathod-sahaab unfortunately, your patch won't work with the new directory structure. Do you want to update it, because it looks like it's acceptable. Otherwise, we will do it for you.

Sure! as currently I won't be able make required changes.

**Comment by drossberg** [comment]
Merged with commit 96659cfdc617874e70d052c6c6a17c20ed398c46.
Thanks @rathod-sahaab!

**Pull request closed without merging**
