### PR TITLE
Fixes Email server validation 

### PR DESCRIPTION
**Pull request by theamanjs**
Fixes Email server validation issue and prevents the user from login and signup if the email server is not set up. The description is mentioned in issue #57

### CODE REVIEW

**Comment by drossberg** [comment]
Does this work for a local mail configuration too? For example with sendmail (https://docs.freebsd.org/en/books/handbook/mail/#sendmail). There, the web-server "simply" sends an email and sendmail manages the connections to other servers. Maybe, this can be considered like an SMTP server at localhost, but username and password shouldn't be necessary, because the local credentials of the web-server user (e.g. www-data) are used.

**Comment by theamanjs** [comment]
I think If we need to make the OGV be able to use this we need to make some changes in code. We can add another variable of `localSMTP` or something similar which will skip the check of password and username. If you say, I can make these changes done.

**Comment by drossberg** [comment]
From what I know is that it's not unusual to use a system mail configuration via a mail program (e.g. "mail" or a Perl mail module). If the server needs a special SMTP server, this mail program had to be special. However, maybe with another patch.

**Comment by theamanjs** [comment]
Okay, so we can merge this pull request and add this thing in future scope?

**Pull request merged**
