### PR TITLE
Backend

### PR DESCRIPTION
**Pull request by meShubham99**
merged all backend work

### CODE REVIEW

**Comment by inderpreetsingh** [comment]
I have merged this, thanks shubham. Can you please clone this and test if your changes are working fine. After that I will merge the front end work too.

**Comment by meShubham99** [comment]
Thanks Inder,
I had a quick check, everything seems to be merged I guess.

**Comment by meShubham99** [comment]
There seems to be some problem though. Umm, my branch shows 50 commits. 
Earlier commits seem to be missing

**Comment by meShubham99** [comment]
Okay I saw that you merged my earlier PRs seperately. Thanks.

**Pull request merged**
