### PR TITLE
Added Blog

### PR DESCRIPTION
**Pull request by zaverichintan**
**Added Blog which can be accessed through**
/blog - normal user 
/admin/blog - admin user

**Features-**
- Comments system
- RSS Feed
- Bootstrap support

### CODE REVIEW

**Comment by inderpreetsingh** [comment]
Hi, thanks chintan. I appreciate it. However we will be using wordpress or ghost for the blog as meteor is not very good on the SEO side. Yeah there are solutions but still, BRL-CAD has it's own blogging platform and you are invited to help in that. However for meteor I don't think a blog would be very useful. Anyway thanks for the patch, I would really love to see a patch in the rendering or the backend part. 

Thanks again :)

**Comment by zaverichintan** [comment]
Hey, I understand that, I am following https://docs.google.com/spreadsheets/d/1a-3FoLLMUr3-9Om_K_XJFsqLjMxlX1G_T4xBbVyk8xk/edit  
Right now. SEO side is going improving. 
WordPress is not secured.

**Comment by zaverichintan** [comment]
For datGUI, it's there in the code base but it is not rendering on the screen, is there some issue? Help me with it. 
I am working on wireframe option with key shortcut.

**Comment by zaverichintan** [comment]
I was looking forward to this 
https://github.com/DerMambo/ms-seo/blob/master/README.md
For SEO propose., kindly help out by suggesting

**Comment by brlcad** [comment]
SEO is not a priority.

**Comment by chauhanshubham** [comment]
@zaverichintan  @inderpreetsingh @brlcad I agree with Inder there, Blog and news at the admin's part, as you see in the "todo ideas link" I provided was a priority level 2 thing (which means after everything basic is done). 
Also, can you provide a link to your repo and branch where you are maintaining all the code related to your patch work. 
Thanks :smile:

**Comment by zaverichintan** [comment]
I am maintaining my work at 
https://github.com/zaverichintan/OGV-meteor
I thought of making this patch as it can be easily verified, and it is useful to users. 
I will start working on making models private and create another PR. 
Thanx for your response.

**Comment by chauhanshubham** [comment]
@zaverichintan datGUI works beautifully at my end. Let me know what issues you were facing. Mail me on the mailing list or sync up on the IRC. Don't follow up on this thread regarding the datGUI topic.

**Pull request closed without merging**
