### PR TITLE
Upgrade and changing the textarea to disable resize

### PR DESCRIPTION
**Pull request by zaverichintan**
Upgrading the meteor and changing CSS file to make text area resize disabled.

### CODE REVIEW

**Comment by inderpreetsingh** [comment]
Hi, good PR. Can you please send it to GSOC-2015-merged branch (https://github.com/BRL-CAD/OGV-meteor/tree/GSOC2015-merged) that's where all our code lies.

**Comment by zaverichintan** [comment]
Hey can I take up the work of cleaning up of all the repos?

**Comment by inderpreetsingh** [comment]
@zaverichintan yeah I would love that. Please!

**Comment by inderpreetsingh** [comment]
Outdated. Can be reopened if required.

**Pull request closed without merging**
